name: Build Tobira RPM

on:
  push:
    tags:
      - '*.*'   # Matches tags like 1.2, 3.5.1, etc.

jobs:
  build-rpm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install RPM tools
        run: |
          sudo apt update
          sudo apt install -y rpm rpm2cpio cpio

      - name: Create RPM build environment
        run: |
          mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}

      - name: Set version from tag
        run: |
          echo "TOBIRA_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Download Tobira binary and config
        run: |
          curl -L -o ~/rpmbuild/SOURCES/tobira-x86_64-unknown-linux-gnu https://github.com/elan-ev/tobira/releases/download/v$TOBIRA_VERSION/tobira-x86_64-unknown-linux-gnu
          curl -L -o ~/rpmbuild/SOURCES/config.toml https://github.com/elan-ev/tobira/releases/download/v$TOBIRA_VERSION/config.toml
          chmod +x ~/rpmbuild/SOURCES/tobira-x86_64-unknown-linux-gnu

      - name: Copy spec file
        run: |
          cp .github/rpm/tobira.spec ~/rpmbuild/SPECS/tobira.spec

      - name: Build RPM
        run: |
          rpmbuild --define "_topdir $HOME/rpmbuild" \
                   --define "tobira_version ${TOBIRA_VERSION}" \
                   -bb ~/rpmbuild/SPECS/tobira.spec

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Tobira ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Debug file path
        run: |
          echo "Looking for: $HOME/rpmbuild/RPMS/x86_64/tobira-${TOBIRA_VERSION}-1.x86_64.rpm"
          ls -lah $HOME/rpmbuild/RPMS/x86_64/

      - name: Move RPM to workspace
        run: |
          mkdir -p ./dist
          cp $HOME/rpmbuild/RPMS/x86_64/tobira-${TOBIRA_VERSION}-1.x86_64.rpm ./dist/

      - name: Upload RPM to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/tobira-${{ env.TOBIRA_VERSION }}-1.x86_64.rpm
          asset_name: tobira-${{ env.TOBIRA_VERSION }}-1.x86_64.rpm
          asset_content_type: application/x-rpm